# Generated by Django 5.1 on 2024-08-21 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img_url', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('past', 'Past'), ('present', 'Present'), ('future', 'Future'), ('eternal', 'Eternal'), ('beyond', 'Beyond')], max_length=10)),
                ('note', models.IntegerField()),
                ('chart_constant', models.FloatField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptt_calculator.song')),
            ],
        ),
    ]
