# Generated by Django 5.1 on 2024-08-29 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt_calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='level',
            field=models.CharField(choices=[('Past', 'PST'), ('Present', 'PRS'), ('Future', 'FTR'), ('Eternal', 'ETR'), ('Beyond', 'BYD'), ('Moment', 'MOM'), ('Eternity', 'ETE')], max_length=10),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.IntegerField()),
                ('score', models.FloatField()),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ptt_calculator.difficulty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
